swagger: 2.0
info:
  version: 1.0
  title: FreightDevApi_Carrier
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: '{DefaultParameterValue}'
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /offers:
    post:
      description: 'TODO: Add Description'
      summary: Add New Offer
      tags:
      - Misc
      operationId: Add New Offer
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AddNewOfferrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /offers
          headers:
            Content-Type: application/json
          body: >-
            {
              "payment" : {
                "price" : {
                  "value" : 1500,
                  "currency" : "PLN"
                }
              },
              "freight": 282,
              "comment": "promocja",
              "carrier" : {
                "id" : "3334"
              },
              "status" : "in_progress",
              "version" : 1
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Add New Offer
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /api/rest/v1/offers/46:
    put:
      description: 'TODO: Add Description'
      summary: Edit offer
      tags:
      - Misc
      operationId: Edit offer
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditOfferrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /api/rest/v1/offers/46
          headers:
            Content-Type: application/json
          body: >-
            {
              "payment" : {
                "price" : {
                  "value" : 4000,
                  "currency" : "PLN"
                }
              },
              "order": 404,
              "comment": "super",
              "carrier" : {
                "id" : "3334"
              },
              "status" : "in_progress"
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Edit offer
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /api/rest/v1/offers/45:
    delete:
      description: 'TODO: Add Description'
      summary: Delete Offer
      tags:
      - Misc
      operationId: Delete Offer
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /api/rest/v1/offers/45
          headers:
            Content-Type: application/json
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete Offer
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /freight-carrier/{carrier_id}/freight/273:
    get:
      description: 'TODO: Add Description'
      summary: Get All Carrier Offers
      tags:
      - Misc
      operationId: Get All Carrier Offers
      produces:
      - application/json
      parameters:
      - name: carrier_id
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  AddNewOfferrequest:
    title: Add New OfferRequest
    type: object
    properties:
      payment:
        description: ''
        $ref: '#/definitions/Payment'
      freight:
        description: ''
        type: integer
        format: int32
      comment:
        description: ''
        type: string
      carrier:
        description: ''
        $ref: '#/definitions/Carrier'
      status:
        description: ''
        type: string
      version:
        description: ''
        type: integer
        format: int32
    required:
    - payment
    - freight
    - comment
    - carrier
    - status
    - version
  Payment:
    title: Payment
    type: object
    properties:
      price:
        description: ''
        $ref: '#/definitions/Price'
    required:
    - price
  Price:
    title: Price
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      currency:
        description: ''
        type: string
    required:
    - value
    - currency
  Carrier:
    title: Carrier
    type: object
    properties:
      id:
        description: ''
        type: string
    required:
    - id
  EditOfferrequest:
    title: Edit offerRequest
    type: object
    properties:
      payment:
        description: ''
        $ref: '#/definitions/Payment'
      order:
        description: ''
        type: integer
        format: int32
      comment:
        description: ''
        type: string
      carrier:
        description: ''
        $ref: '#/definitions/Carrier'
      status:
        description: ''
        type: string
    required:
    - payment
    - order
    - comment
    - carrier
    - status
