swagger: '2.0'
info:
  version: '1.0'
  title: Freights Carrier
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /offers:
    post:
      description: 'TODO: Add Description'
      summary: Add New Offer
      tags:
      - Misc
      operationId: Add New Offer
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AddNewOfferrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /freight-carrier:
    get:
      description: 'TODO: Add Description'
      summary: Get All Carrier Freights
      tags:
      - Misc
      operationId: Get All Carrier Freights
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: GET
          uri: /freight-carrier
          headers:
            Authorization: '{{auth_token}}'
            Content-Type: application/json
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get All Carrier Freights
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /offers/131:
    put:
      description: 'TODO: Add Description'
      summary: Reject offer
      tags:
      - Misc
      operationId: Reject offer
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/RejectOfferrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: PUT
          uri: /offers/131
          headers:
            Content-Type: application/json
            Authorization: '{{auth_token}}'
          body: >-
            {
              "payment" : {
                "price" : {
                  "value" : 1000,
                  "currency" : "PLN"
                }
              },
              "comment": "sale",
              "version" : 2
              }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Reject offer
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  AddNewOfferrequest:
    title: Add New OfferRequest
    type: object
    properties:
      payment:
        $ref: '#/definitions/Payment'
      freight:
        description: ''
        type: integer
        format: int32
      comment:
        description: ''
        type: string
      version:
        description: ''
        type: integer
        format: int32
    required:
    - payment
    - freight
    - comment
    - version
  Payment:
    title: Payment
    type: object
    properties:
      price:
        $ref: '#/definitions/Price'
    required:
    - price
  Price:
    title: Price
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      currency:
        description: ''
        type: string
    required:
    - value
    - currency
  UpdateOfferrequest:
    title: Update offerRequest
    example:
      payment:
        price:
          value: 1000
          currency: PLN
      comment: sale
      version: 2
    type: object
    properties:
      payment:
        $ref: '#/definitions/Payment'
      comment:
        description: ''
        type: string
      version:
        description: ''
        type: integer
        format: int32
    required:
    - payment
    - comment
    - version
  RejectOfferrequest:
    title: Reject offerRequest
    example:
      payment:
        price:
          value: 1000
          currency: PLN
      comment: sale
      version: 2
    type: object
    properties:
      payment:
        $ref: '#/definitions/Payment'
      comment:
        description: ''
        type: string
      version:
        description: ''
        type: integer
        format: int32
    required:
    - payment
    - comment
    - version
