swagger: 2.0
info:
  version: 1.0
  title: ShipmentRequests
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: '{DefaultParameterValue}'
basePath: /
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: ''
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /shipment-requests/{shipper_id}:
    post:
      description: 'TODO: Add Description'
      summary: Add New ShipmentRequests
      tags:
      - Misc
      operationId: Add New ShipmentRequests
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AddNewShipmentrequestsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: shipper_id
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /shipment-requests:
    get:
      description: 'TODO: Add Description'
      summary: Get All User ShipmentRequests
      tags:
      - Misc
      operationId: Get All User ShipmentRequests
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /shipment-requests
          headers:
            Authorization: Bearer 1c24bed0e8be4da36f825fc55937f5f7aa560d2a
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get All User ShipmentRequests
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /api/rest/v1/shipment-requests:
    put:
      description: 'TODO: Add Description'
      summary: Edit ShipmentReqests
      tags:
      - Misc
      operationId: Edit ShipmentReqests
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/EditShipmentreqestsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      description: 'TODO: Add Description'
      summary: Delete ShipmentReqests
      tags:
      - Misc
      operationId: Delete ShipmentReqests
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /api/rest/v1/shipment-requests
          headers:
            Content-Type: application/json
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete ShipmentReqests
        x-testDescription: 'TODO: Add Description'
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /shipment-requests/{shipper_id}/309:
    patch:
      description: 'TODO: Add Description'
      summary: SR add/update Freights
      tags:
      - Misc
      operationId: SR add/update Freights
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/SrAdd~1updateFreightsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: shipper_id
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  AddNewShipmentrequestsrequest:
    title: Add New ShipmentRequestsRequest
    type: object
    properties:
      name:
        description: ''
        type: string
      number:
        description: ''
        type: string
      status:
        description: ''
        type: string
      freights:
        description: ''
        type: array
        items:
          type: string
      spots:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Spot'
      loads:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Load'
    required:
    - name
    - number
    - status
    - freights
    - spots
    - loads
  Spot:
    title: Spot
    type: object
    properties:
      name:
        description: ''
        type: string
      type:
        description: ''
        type: string
      timespans:
        description: ''
        $ref: '#/definitions/Timespans'
      place:
        description: ''
        $ref: '#/definitions/Place'
    required:
    - name
    - type
    - timespans
    - place
  Timespans:
    title: Timespans
    type: object
    properties:
      begin:
        description: ''
        type: string
      end:
        description: ''
        type: string
    required:
    - begin
    - end
  Place:
    title: Place
    type: object
    properties:
      address:
        description: ''
        $ref: '#/definitions/Address'
      coordinates:
        description: ''
        $ref: '#/definitions/Coordinates'
    required:
    - address
    - coordinates
  Address:
    title: Address
    type: object
    properties:
      locality:
        description: ''
        type: string
      postal_code:
        description: ''
        type: string
      country:
        description: ''
        type: string
      street:
        description: ''
        type: string
      number:
        description: ''
        type: string
    required:
    - locality
    - postal_code
    - country
    - street
    - number
  Coordinates:
    title: Coordinates
    type: object
    properties:
      latitude:
        description: ''
        type: number
        format: double
      longitude:
        description: ''
        type: number
        format: double
    required:
    - latitude
    - longitude
  Load:
    title: Load
    type: object
    properties:
      name:
        description: ''
        type: string
      description:
        description: ''
        type: string
      type_of_load:
        description: ''
        type: string
      weight:
        description: ''
        $ref: '#/definitions/Weight'
      height:
        description: ''
        $ref: '#/definitions/Height'
      width:
        description: ''
        $ref: '#/definitions/Width'
      length:
        description: ''
        $ref: '#/definitions/Length'
      volume:
        description: ''
        $ref: '#/definitions/Volume'
      amount:
        description: ''
        type: integer
        format: int32
      requirements:
        description: ''
        $ref: '#/definitions/Requirements'
    required:
    - name
    - description
    - type_of_load
    - weight
    - height
    - width
    - length
    - volume
    - amount
    - requirements
  Weight:
    title: Weight
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      unit_code:
        description: ''
        type: string
    required:
    - value
    - unit_code
  Height:
    title: Height
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      unit_code:
        description: ''
        type: string
    required:
    - value
    - unit_code
  Width:
    title: Width
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      unit_code:
        description: ''
        type: string
    required:
    - value
    - unit_code
  Length:
    title: Length
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      unit_code:
        description: ''
        type: string
    required:
    - value
    - unit_code
  Volume:
    title: Volume
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      unit_code:
        description: ''
        type: string
    required:
    - value
    - unit_code
  Requirements:
    title: Requirements
    type: object
    properties:
      required_adr_classes:
        description: ''
        type: array
        items:
          type: string
      required_ways_of_loading:
        description: ''
        type: array
        items:
          type: string
      required_truck_bodies:
        description: ''
        type: array
        items:
          type: string
      is_truck_crane_required:
        description: ''
        type: boolean
      is_lift_required:
        description: ''
        type: boolean
      is_for_clearance:
        description: ''
        type: boolean
      is_tir_cable_required:
        description: ''
        type: boolean
      is_ftl:
        description: ''
        type: boolean
      is_tracking_system_required:
        description: ''
        type: boolean
      shipping_remarks:
        description: ''
        type: string
    required:
    - required_adr_classes
    - required_ways_of_loading
    - required_truck_bodies
    - is_truck_crane_required
    - is_lift_required
    - is_for_clearance
    - is_tir_cable_required
    - is_ftl
    - is_tracking_system_required
    - shipping_remarks
  EditShipmentreqestsrequest:
    title: Edit ShipmentReqestsRequest
    type: object
    properties:
      name:
        description: ''
        type: string
      number:
        description: ''
        type: string
      status:
        description: ''
        type: string
      freights:
        description: ''
        type: array
        items:
          type: string
      spots:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Spot'
      loads:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Load19'
    required:
    - name
    - number
    - status
    - freights
    - spots
    - loads
  Load19:
    title: Load19
    type: object
    properties:
      id:
        description: ''
        type: integer
        format: int32
      name:
        description: ''
        type: string
      description:
        description: ''
        type: string
      type_of_load:
        description: ''
        type: string
      weight:
        description: ''
        $ref: '#/definitions/Weight'
      height:
        description: ''
        $ref: '#/definitions/Height'
      width:
        description: ''
        $ref: '#/definitions/Width'
      length:
        description: ''
        $ref: '#/definitions/Length'
      volume:
        description: ''
        $ref: '#/definitions/Volume'
      amount:
        description: ''
        type: integer
        format: int32
      requirements:
        description: ''
        $ref: '#/definitions/Requirements'
    required:
    - id
    - name
    - description
    - type_of_load
    - weight
    - height
    - width
    - length
    - volume
    - amount
    - requirements
  SrAdd/updateFreightsrequest:
    title: SR add/update FreightsRequest
    type: object
    properties:
      freights:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Freight'
    required:
    - freights
  Freight:
    title: Freight
    type: object
    properties:
      id:
        description: ''
        type: integer
        format: int32
      number:
        description: ''
        type: string
      publish_date:
        description: ''
        type: string
      publish_type:
        description: ''
        type: string
      send_to_stock:
        description: ''
        type: boolean
      type:
        description: ''
        type: string
      status:
        description: ''
        type: string
      carriers:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Carrier'
      shipper:
        description: ''
        $ref: '#/definitions/Shipper'
      spots:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Spot'
      payment:
        description: ''
        $ref: '#/definitions/Payment'
      decision_date:
        description: ''
        type: string
      loads:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Load39'
    required:
    - id
    - number
    - publish_date
    - publish_type
    - send_to_stock
    - type
    - status
    - carriers
    - shipper
    - spots
    - payment
    - decision_date
    - loads
  Carrier:
    title: Carrier
    type: object
    properties:
      company:
        description: ''
        $ref: '#/definitions/Company'
    required:
    - company
  Company:
    title: Company
    type: object
    properties:
      id:
        description: ''
        type: integer
        format: int32
    required:
    - id
  Shipper:
    title: Shipper
    type: object
    properties:
      company:
        description: ''
        $ref: '#/definitions/Company31'
    required:
    - company
  Company31:
    title: Company31
    type: object
    properties:
      id:
        description: ''
        type: string
    required:
    - id
  Payment:
    title: Payment
    type: object
    properties:
      price:
        description: ''
        $ref: '#/definitions/Price'
    required:
    - price
  Price:
    title: Price
    type: object
    properties:
      value:
        description: ''
        type: integer
        format: int32
      currency:
        description: ''
        type: string
    required:
    - value
    - currency
  Load39:
    title: Load39
    type: object
    properties:
      shipment_request_load_id:
        description: ''
        type: integer
        format: int32
      name:
        description: ''
        type: string
      description:
        description: ''
        type: string
      type_of_load:
        description: ''
        type: string
      weight:
        description: ''
        $ref: '#/definitions/Weight'
      height:
        description: ''
        $ref: '#/definitions/Height'
      width:
        description: ''
        $ref: '#/definitions/Width'
      length:
        description: ''
        $ref: '#/definitions/Length'
      volume:
        description: ''
        $ref: '#/definitions/Volume'
      amount:
        description: ''
        type: integer
        format: int32
      requirements:
        description: ''
        $ref: '#/definitions/Requirements45'
    required:
    - shipment_request_load_id
    - name
    - description
    - type_of_load
    - weight
    - height
    - width
    - length
    - volume
    - amount
    - requirements
  Requirements45:
    title: Requirements45
    type: object
    properties:
      required_adr_classes:
        description: ''
        type: array
        items:
          type: string
      required_ways_of_loading:
        description: ''
        type: array
        items:
          type: string
      required_truck_bodies:
        description: ''
        type: integer
        format: int32
      is_truck_crane_required:
        description: ''
        type: boolean
      is_lift_required:
        description: ''
        type: boolean
      is_for_clearance:
        description: ''
        type: boolean
      is_tir_cable_required:
        description: ''
        type: boolean
      is_ftl:
        description: ''
        type: boolean
      is_tracking_system_required:
        description: ''
        type: boolean
      shipping_remarks:
        description: ''
        type: string
    required:
    - required_adr_classes
    - required_ways_of_loading
    - required_truck_bodies
    - is_truck_crane_required
    - is_lift_required
    - is_for_clearance
    - is_tir_cable_required
    - is_ftl
    - is_tracking_system_required
    - shipping_remarks
